'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class DisplayText
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GUI.DisplayText", GetType(DisplayText).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to About {0}.
        '''</summary>
        Friend Shared ReadOnly Property About() As String
            Get
                Return ResourceManager.GetString("About", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alberto.
        '''</summary>
        Friend Shared ReadOnly Property Alberto() As String
            Get
                Return ResourceManager.GetString("Alberto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ammo.
        '''</summary>
        Friend Shared ReadOnly Property Ammo() As String
            Get
                Return ResourceManager.GetString("Ammo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ammo Calibers.
        '''</summary>
        Friend Shared ReadOnly Property AmmoCalibers() As String
            Get
                Return ResourceManager.GetString("AmmoCalibers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ammo Drop Rates.
        '''</summary>
        Friend Shared ReadOnly Property AmmoDropRates() As String
            Get
                Return ResourceManager.GetString("AmmoDropRates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ammo Flags.
        '''</summary>
        Friend Shared ReadOnly Property AmmoFlags() As String
            Get
                Return ResourceManager.GetString("AmmoFlags", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ammo Types.
        '''</summary>
        Friend Shared ReadOnly Property AmmoTypes() As String
            Get
                Return ResourceManager.GetString("AmmoTypes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Application Starting....
        '''</summary>
        Friend Shared ReadOnly Property ApplicationStarting() As String
            Get
                Return ResourceManager.GetString("ApplicationStarting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Armour Classes.
        '''</summary>
        Friend Shared ReadOnly Property ArmourClasses() As String
            Get
                Return ResourceManager.GetString("ArmourClasses", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Armour Drop Rates.
        '''</summary>
        Friend Shared ReadOnly Property ArmourDropRates() As String
            Get
                Return ResourceManager.GetString("ArmourDropRates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Armours.
        '''</summary>
        Friend Shared ReadOnly Property Armours() As String
            Get
                Return ResourceManager.GetString("Armours", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Arnie.
        '''</summary>
        Friend Shared ReadOnly Property Arnie() As String
            Get
                Return ResourceManager.GetString("Arnie", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Attachment Classes.
        '''</summary>
        Friend Shared ReadOnly Property AttachmentClasses() As String
            Get
                Return ResourceManager.GetString("AttachmentClasses", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Attachment Info.
        '''</summary>
        Friend Shared ReadOnly Property AttachmentInfo() As String
            Get
                Return ResourceManager.GetString("AttachmentInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Attachment Listing.
        '''</summary>
        Friend Shared ReadOnly Property AttachmentList() As String
            Get
                Return ResourceManager.GetString("AttachmentList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Attachment Merges.
        '''</summary>
        Friend Shared ReadOnly Property AttachmentMerges() As String
            Get
                Return ResourceManager.GetString("AttachmentMerges", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Attachment Points.
        '''</summary>
        Friend Shared ReadOnly Property AttachmentPoints() As String
            Get
                Return ResourceManager.GetString("AttachmentPoints", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Attachments.
        '''</summary>
        Friend Shared ReadOnly Property Attachments() As String
            Get
                Return ResourceManager.GetString("Attachments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Attachment Slots.
        '''</summary>
        Friend Shared ReadOnly Property AttachmentSlots() As String
            Get
                Return ResourceManager.GetString("AttachmentSlots", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Attachment System.
        '''</summary>
        Friend Shared ReadOnly Property AttachmentSystem() As String
            Get
                Return ResourceManager.GetString("AttachmentSystem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Building Item Table....
        '''</summary>
        Friend Shared ReadOnly Property BuildingItemTable() As String
            Get
                Return ResourceManager.GetString("BuildingItemTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Burst Sounds.
        '''</summary>
        Friend Shared ReadOnly Property BurstSounds() As String
            Get
                Return ResourceManager.GetString("BurstSounds", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Carlo.
        '''</summary>
        Friend Shared ReadOnly Property Carlo() As String
            Get
                Return ResourceManager.GetString("Carlo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clothes.
        '''</summary>
        Friend Shared ReadOnly Property Clothes() As String
            Get
                Return ResourceManager.GetString("Clothes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compatible Facial Gear.
        '''</summary>
        Friend Shared ReadOnly Property CompatibleFaceItems() As String
            Get
                Return ResourceManager.GetString("CompatibleFaceItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Creating database....
        '''</summary>
        Friend Shared ReadOnly Property CreatingDatabase() As String
            Get
                Return ResourceManager.GetString("CreatingDatabase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current Dir: {0}.
        '''</summary>
        Friend Shared ReadOnly Property CurrentDirectorySplash() As String
            Get
                Return ResourceManager.GetString("CurrentDirectorySplash", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cursors.
        '''</summary>
        Friend Shared ReadOnly Property Cursors() As String
            Get
                Return ResourceManager.GetString("Cursors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Custom Filter.
        '''</summary>
        Friend Shared ReadOnly Property CustomFilter() As String
            Get
                Return ResourceManager.GetString("CustomFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data.
        '''</summary>
        Friend Shared ReadOnly Property Data() As String
            Get
                Return ResourceManager.GetString("Data", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Devin.
        '''</summary>
        Friend Shared ReadOnly Property Devin() As String
            Get
                Return ResourceManager.GetString("Devin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Drugs.
        '''</summary>
        Friend Shared ReadOnly Property Drugs() As String
            Get
                Return ResourceManager.GetString("Drugs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Drug Types.
        '''</summary>
        Friend Shared ReadOnly Property DrugTypes() As String
            Get
                Return ResourceManager.GetString("DrugTypes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Elgin.
        '''</summary>
        Friend Shared ReadOnly Property Elgin() As String
            Get
                Return ResourceManager.GetString("Elgin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enemy Ammo Choices.
        '''</summary>
        Friend Shared ReadOnly Property EnemyAmmo() As String
            Get
                Return ResourceManager.GetString("EnemyAmmo", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Enemy Gun Choices.
        '''</summary>
        Friend Shared ReadOnly Property EnemyGuns() As String
            Get
                Return ResourceManager.GetString("EnemyGuns", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Enemy Item Choices.
        '''</summary>
        Friend Shared ReadOnly Property EnemyItems() As String
            Get
                Return ResourceManager.GetString("EnemyItems", resourceCulture)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized string similar to Enemy Gun Choices.
        '''</summary>
        Friend Shared ReadOnly Property MilitiaGuns() As String
            Get
                Return ResourceManager.GetString("Militiauns", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Enemy Item Choices.
        '''</summary>
        Friend Shared ReadOnly Property MilitiaItems() As String
            Get
                Return ResourceManager.GetString("MilitiaItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to English.
        '''</summary>
        Friend Shared ReadOnly Property English() As String
            Get
                Return ResourceManager.GetString("English", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Explosions.
        '''</summary>
        Friend Shared ReadOnly Property Explosions() As String
            Get
                Return ResourceManager.GetString("Explosions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Explosion Types.
        '''</summary>
        Friend Shared ReadOnly Property ExplosionTypes() As String
            Get
                Return ResourceManager.GetString("ExplosionTypes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Explosive Drop Rates.
        '''</summary>
        Friend Shared ReadOnly Property ExplosiveDropRates() As String
            Get
                Return ResourceManager.GetString("ExplosiveDropRates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Explosives.
        '''</summary>
        Friend Shared ReadOnly Property Explosives() As String
            Get
                Return ResourceManager.GetString("Explosives", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Facial Gear.
        '''</summary>
        Friend Shared ReadOnly Property FaceGear() As String
            Get
                Return ResourceManager.GetString("FaceGear", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Food.
        '''</summary>
        Friend Shared ReadOnly Property Food() As String
            Get
                Return ResourceManager.GetString("Food", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Frank.
        '''</summary>
        Friend Shared ReadOnly Property Frank() As String
            Get
                Return ResourceManager.GetString("Frank", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Franz.
        '''</summary>
        Friend Shared ReadOnly Property Franz() As String
            Get
                Return ResourceManager.GetString("Franz", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fredo.
        '''</summary>
        Friend Shared ReadOnly Property Fredo() As String
            Get
                Return ResourceManager.GetString("Fredo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gabby.
        '''</summary>
        Friend Shared ReadOnly Property Gabby() As String
            Get
                Return ResourceManager.GetString("Gabby", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Grenades.
        '''</summary>
        Friend Shared ReadOnly Property Grenades() As String
            Get
                Return ResourceManager.GetString("Grenades", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Guns.
        '''</summary>
        Friend Shared ReadOnly Property Guns() As String
            Get
                Return ResourceManager.GetString("Guns", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Herve.
        '''</summary>
        Friend Shared ReadOnly Property Herve() As String
            Get
                Return ResourceManager.GetString("Herve", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Howard.
        '''</summary>
        Friend Shared ReadOnly Property Howard() As String
            Get
                Return ResourceManager.GetString("Howard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IMP Item Choices.
        '''</summary>
        Friend Shared ReadOnly Property ImpItems() As String
            Get
                Return ResourceManager.GetString("ImpItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Incompatible Attachments.
        '''</summary>
        Friend Shared ReadOnly Property IncompatibleAttachments() As String
            Get
                Return ResourceManager.GetString("IncompatibleAttachments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Initializing....
        '''</summary>
        Friend Shared ReadOnly Property Initializing() As String
            Get
                Return ResourceManager.GetString("Initializing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inventory.
        '''</summary>
        Friend Shared ReadOnly Property Inventory() As String
            Get
                Return ResourceManager.GetString("Inventory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inventory Silhouettes.
        '''</summary>
        Friend Shared ReadOnly Property InventorySilhouettes() As String
            Get
                Return ResourceManager.GetString("InventorySilhouettes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item Classes.
        '''</summary>
        Friend Shared ReadOnly Property ItemClasses() As String
            Get
                Return ResourceManager.GetString("ItemClasses", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}: Item - {1} - {2}.
        '''</summary>
        Friend Shared ReadOnly Property ItemDataFormText() As String
            Get
                Return ResourceManager.GetString("ItemDataFormText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item Flags.
        '''</summary>
        Friend Shared ReadOnly Property ItemFlags() As String
            Get
                Return ResourceManager.GetString("ItemFlags", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Items.
        '''</summary>
        Friend Shared ReadOnly Property Items() As String
            Get
                Return ResourceManager.GetString("Items", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item Transformations.
        '''</summary>
        Friend Shared ReadOnly Property ItemTransformations() As String
            Get
                Return ResourceManager.GetString("ItemTransformations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jake.
        '''</summary>
        Friend Shared ReadOnly Property Jake() As String
            Get
                Return ResourceManager.GetString("Jake", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Keith.
        '''</summary>
        Friend Shared ReadOnly Property Keith() As String
            Get
                Return ResourceManager.GetString("Keith", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Keys.
        '''</summary>
        Friend Shared ReadOnly Property Keys() As String
            Get
                Return ResourceManager.GetString("Keys", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kits.
        '''</summary>
        Friend Shared ReadOnly Property Kits() As String
            Get
                Return ResourceManager.GetString("Kits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Knives.
        '''</summary>
        Friend Shared ReadOnly Property Knives() As String
            Get
                Return ResourceManager.GetString("Knives", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Launchables.
        '''</summary>
        Friend Shared ReadOnly Property Launchables() As String
            Get
                Return ResourceManager.GetString("Launchables", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Launchers.
        '''</summary>
        Friend Shared ReadOnly Property Launchers() As String
            Get
                Return ResourceManager.GetString("Launchers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Load Bearing Equipment Classes.
        '''</summary>
        Friend Shared ReadOnly Property LbeClasses() As String
            Get
                Return ResourceManager.GetString("LbeClasses", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LoadBearing.
        '''</summary>
        Friend Shared ReadOnly Property LoadBearing() As String
            Get
                Return ResourceManager.GetString("LoadBearing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading....
        '''</summary>
        Friend Shared ReadOnly Property Loading() As String
            Get
                Return ResourceManager.GetString("Loading", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading Images....
        '''</summary>
        Friend Shared ReadOnly Property LoadingImages() As String
            Get
                Return ResourceManager.GetString("LoadingImages", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading Saved Settings....
        '''</summary>
        Friend Shared ReadOnly Property LoadingSettings() As String
            Get
                Return ResourceManager.GetString("LoadingSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading XML Files... {1}.
        '''</summary>
        Friend Shared ReadOnly Property LoadingTables() As String
            Get
                Return ResourceManager.GetString("LoadingTables", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading XML Files....
        '''</summary>
        Friend Shared ReadOnly Property LoadingXmlFiles() As String
            Get
                Return ResourceManager.GetString("LoadingXmlFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JA2 v1.13 - XML Editor (Current Directory: {0}).
        '''</summary>
        Friend Shared ReadOnly Property MainFormTitle() As String
            Get
                Return ResourceManager.GetString("MainFormTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Manny.
        '''</summary>
        Friend Shared ReadOnly Property Manny() As String
            Get
                Return ResourceManager.GetString("Manny", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}: Starting Gear - {1}.
        '''</summary>
        Friend Shared ReadOnly Property MercGearDataFormText() As String
            Get
                Return ResourceManager.GetString("MercGearDataFormText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Merc Starting Gear.
        '''</summary>
        Friend Shared ReadOnly Property MercStartingGear() As String
            Get
                Return ResourceManager.GetString("MercStartingGear", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Merge Types.
        '''</summary>
        Friend Shared ReadOnly Property MergeTypes() As String
            Get
                Return ResourceManager.GetString("MergeTypes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mickey.
        '''</summary>
        Friend Shared ReadOnly Property Mickey() As String
            Get
                Return ResourceManager.GetString("Mickey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Miscellaneous.
        '''</summary>
        Friend Shared ReadOnly Property Misc() As String
            Get
                Return ResourceManager.GetString("Misc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Misc. Item Drop Rates.
        '''</summary>
        Friend Shared ReadOnly Property MiscItemDropRates() As String
            Get
                Return ResourceManager.GetString("MiscItemDropRates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NAS Attachment Classes.
        '''</summary>
        Friend Shared ReadOnly Property NasAttachmentClasses() As String
            Get
                Return ResourceManager.GetString("NasAttachmentClasses", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to None.
        '''</summary>
        Friend Shared ReadOnly Property None() As String
            Get
                Return ResourceManager.GetString("None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Normal Guns Mode.
        '''</summary>
        Friend Shared ReadOnly Property NormalGunsMode() As String
            Get
                Return ResourceManager.GetString("NormalGunsMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Other.
        '''</summary>
        Friend Shared ReadOnly Property Other() As String
            Get
                Return ResourceManager.GetString("Other", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Other Weapons.
        '''</summary>
        Friend Shared ReadOnly Property OtherWeapons() As String
            Get
                Return ResourceManager.GetString("OtherWeapons", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Perko.
        '''</summary>
        Friend Shared ReadOnly Property Perko() As String
            Get
                Return ResourceManager.GetString("Perko", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Peter.
        '''</summary>
        Friend Shared ReadOnly Property Peter() As String
            Get
                Return ResourceManager.GetString("Peter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pocket Types.
        '''</summary>
        Friend Shared ReadOnly Property PocketTypes() As String
            Get
                Return ResourceManager.GetString("PocketTypes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Random Items.
        '''</summary>
        Friend Shared ReadOnly Property RandomItems() As String
            Get
                Return ResourceManager.GetString("RandomItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Realistic Mode.
        '''</summary>
        Friend Shared ReadOnly Property RealisticMode() As String
            Get
                Return ResourceManager.GetString("RealisticMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reloading Data....
        '''</summary>
        Friend Shared ReadOnly Property ReloadingData() As String
            Get
                Return ResourceManager.GetString("ReloadingData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sam.
        '''</summary>
        Friend Shared ReadOnly Property Sam() As String
            Get
                Return ResourceManager.GetString("Sam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saving....
        '''</summary>
        Friend Shared ReadOnly Property Saving() As String
            Get
                Return ResourceManager.GetString("Saving", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sci-Fi Mode.
        '''</summary>
        Friend Shared ReadOnly Property SciFiMode() As String
            Get
                Return ResourceManager.GetString("SciFiMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Searching for other directories....
        '''</summary>
        Friend Shared ReadOnly Property SearchingForOtherDirectories() As String
            Get
                Return ResourceManager.GetString("SearchingForOtherDirectories", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Separability States.
        '''</summary>
        Friend Shared ReadOnly Property Separability() As String
            Get
                Return ResourceManager.GetString("Separability", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skill Checks.
        '''</summary>
        Friend Shared ReadOnly Property SkillChecks() As String
            Get
                Return ResourceManager.GetString("SkillChecks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sounds.
        '''</summary>
        Friend Shared ReadOnly Property Sounds() As String
            Get
                Return ResourceManager.GetString("Sounds", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Standard Merges.
        '''</summary>
        Friend Shared ReadOnly Property StandardMerges() As String
            Get
                Return ResourceManager.GetString("StandardMerges", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tons of Guns Mode.
        '''</summary>
        Friend Shared ReadOnly Property TonsOfGunsMode() As String
            Get
                Return ResourceManager.GetString("TonsOfGunsMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tony.
        '''</summary>
        Friend Shared ReadOnly Property Tony() As String
            Get
                Return ResourceManager.GetString("Tony", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unhandled error.  Please report this error to the JA2 1.13 Development Team on the &apos;Bears Pit Forum&apos;..
        '''</summary>
        Friend Shared ReadOnly Property UnhandledError() As String
            Get
                Return ResourceManager.GetString("UnhandledError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Version {0}.
        '''</summary>
        Friend Shared ReadOnly Property Version() As String
            Get
                Return ResourceManager.GetString("Version", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Weapon Classes.
        '''</summary>
        Friend Shared ReadOnly Property WeaponClasses() As String
            Get
                Return ResourceManager.GetString("WeaponClasses", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Weapon Drop Rates.
        '''</summary>
        Friend Shared ReadOnly Property WeaponDropRates() As String
            Get
                Return ResourceManager.GetString("WeaponDropRates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Weapon Types.
        '''</summary>
        Friend Shared ReadOnly Property WeaponTypes() As String
            Get
                Return ResourceManager.GetString("WeaponTypes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Welcome to the JA2 v1.13 XML Editor.
        '''</summary>
        Friend Shared ReadOnly Property Welcome() As String
            Get
                Return ResourceManager.GetString("Welcome", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
